blank_issues_enabled: false
contact_links:
  - name: Perguntas gerais
    url: https://github.com/maxDevAndroid/FlyWithMySystemDesign/discussions
    about: Use Discussions para dúvidas, ideias ou debates.
